# Generated by Django 3.1.4 on 2022-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phnNo', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
