# Generated by Django 3.1.4 on 2022-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vApp', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='prodId',
            field=models.CharField(default='0', max_length=90),
        ),
    ]
