# Generated by Django 3.1.4 on 2022-04-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vApp', '0004_orders_prodid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
