# Generated by Django 3.1.4 on 2022-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vApp', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
